### ISSUE TITLE
Getting got_ver is None error when importing

### ISSUE THREAD

**Issue by hwsamuel** [unitaryai/detoxify#18]
I re-installed detoxify to the latest version and now I'm getting the following error when I try `import detoxify`. This has something to do with the transformers and torch dependencies, looks like the latest versions are incompatible

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\detoxify\__init__.py", line 1, in <module>
    from .detoxify import (
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\detoxify\detoxify.py", line 2, in <module>
    import transformers
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\transformers\dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\transformers\utils\versions.py", line 120, in require_version_core
    return require_version(requirement, hint)
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\transformers\utils\versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\transformers\utils\versions.py", line 45, in _compare_versions
    raise ValueError("got_ver is None")
ValueError: got_ver is None
```

**Comment by laurahanu** [comment]
Hello,

Thanks for raising this. It seems to be working with the latest transformers and torch versions for me (4.8.1 and 1.9.0), which versions are you using?

**Comment by hwsamuel** [comment]
Thanks, I tried upgrading to the latest transformers and torch versions you've mentioned, but still getting the same **got_ver** error. If I do a fresh install in a virtual environment, there are no issues then, so probably a conflict with some other package versions (using Anaconda)

**Comment by gingsi** [comment]
The last comment's answer here seems to fix it: https://github.com/huggingface/transformers/issues/13356

Uninstall numpy, delete any remaining `numpy*` folders in pythons `site-packages` folder, install numpy.
